# Generated by Django 6.0.3 on 2026-03-16 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periodic_table', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chemical_formula', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('discovered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_type', models.CharField(choices=[('IONIC', 'Ionic'), ('COVALENT', 'Covalent'), ('METALLIC', 'Metallic'), ('HYDROGEN', 'Hydrogen')], max_length=20)),
                ('count', models.IntegerField(default=1)),
                ('element_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds_as_element_1', to='periodic_table.element')),
                ('element_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds_as_element_2', to='periodic_table.element')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='simulations.material')),
            ],
        ),
    ]
