# Generated by Django 6.0.3 on 2026-03-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=5, unique=True)),
                ('atomic_number', models.IntegerField(unique=True)),
                ('atomic_mass', models.FloatField()),
                ('group', models.IntegerField(blank=True, null=True)),
                ('period', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('electron_configuration', models.CharField(blank=True, max_length=100)),
                ('electronegativity', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['atomic_number'],
            },
        ),
    ]
