# Generated by Django 6.0.3 on 2026-03-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodic_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='atomic_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='boil',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='melt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='phase',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
